### ISSUE TITLE
Conversion does not work with newly released data

### ISSUE THREAD

**Issue by schulmar** [highsource/tenra#1]
The new data under http://download-data.deutschebahn.com/static/datasets/streckennetz/DB_Inspire_XML_2015.zip does not convert with the current release and gives:

```
java -jar tenra-1.0.0.jar DB-Netz_INSPIRE_20160107.xml 
Exception in thread "main" java.lang.IllegalArgumentException: Property [id] is expected to be equal to [:MPost-1269181] but the value is [MPost-1269181]. Parent is [inspire.x.specification.gmlas.commontransportelements._3.MarkerPostType@7e5a5d21[metaDataProperty=<null>(default), description=<null>(default), descriptionReference=<null>(default), identifier=net.opengis.gml.v_3_2_1.CodeWithAuthorityType@597d9abe[value=urn:x-dbnetze:oid:MPost-1269181, codeSpace=http://inspire.jrc.ec.europa.eu/ids], name=<null>(default), id=MPost-1269181, boundedBy=<null>(default), location=<null>(default), beginLifespanVersion=<null>(default), inspireId=inspire.x.specification.gmlas.basetypes._3.IdentifierPropertyType@2f3dc968[identifier=inspire.x.specification.gmlas.basetypes._3.IdentifierType@171e313[localId=MPost-1269181, namespace=DE.DB-NETZE.TN.STREDA, versionId=<{urn:x-inspire:specification:gmlas:BaseTypes:3.2}versionId[inspire.x.specification.gmlas.basetypes._3.IdentifierType$VersionId@5bf2f522[value=, nilReason={other:unpopulated}]]>]], endLifespanVersion=<{urn:x-inspire:specification:gmlas:Network:3.2}endLifespanVersion[inspire.x.specification.gmlas.network._3.NetworkElementType$EndLifespanVersion@2bbbba57[value=<null>(default), nilReason={other:unpopulated}]]>, inNetwork={net.opengis.gml.v_3_2_1.ReferenceType@31c6bc2f[owns=false(default), nilReason=<null>(default), remoteSchema=<null>(default), type=<null>(default), href=urn:x-dbnetze:oid:db-netz, role=<null>(default), arcrole=<null>(default), title=<null>(default), show=<null>(default), actuate=<null>(default)]}, geographicalName=<null>(default), geometry=net.opengis.gml.v_3_2_1.PointPropertyType@6e6ccb30[point=net.opengis.gml.v_3_2_1.PointType@288ff4f3[metaDataProperty=<null>(default), description=<null>(default), descriptionReference=<null>(default), identifier=<null>(default), name=<null>(default), id=kilometer_extern.oid.1269181.geom.Geom_0, srsName=urn:ogc:def:crs:EPSG::4258, srsDimension=2, axisLabels=<null>(default), uomLabels=<null>(default), pos=net.opengis.gml.v_3_2_1.DirectPositionType@75bebe0f[value={54.743783104361,9.383465286309}, srsName=<null>(default), srsDimension=<null>(default), axisLabels=<null>(default), uomLabels=<null>(default)], coordinates=<null>(default)], owns=false(default), nilReason=<null>(default), remoteSchema=<null>(default), type=<null>(default), href=<null>(default), role=<null>(default), arcrole=<null>(default), title=<null>(default), show=<null>(default), actuate=<null>(default)], validFrom=<null>(default), validTo=<{urn:x-inspire:specification:gmlas:CommonTransportElements:3.0}validTo[inspire.x.specification.gmlas.commontransportelements._3.TransportPointType$ValidTo@45de1237[value=<null>(default), nilReason={other:unpopulated}]]>, markerLocation=net.opengis.gml.v_3_2_1.LengthType@767dfcb6[value=171.0, uom=km], route=net.opengis.gml.v_3_2_1.ReferenceType@495a4d80[owns=false(default), nilReason=<null>(default), remoteSchema=<null>(default), type=<null>(default), href=urn:x-dbnetze:oid:Line-1581583, role=<null>(default), arcrole=<null>(default), title=<null>(default), show=<null>(default), actuate=<null>(default)]]].
        at org.hisrc.tenra.util.Ensure.propertyEquals(Ensure.java:70)
        at org.hisrc.tenra.converter.commontransportelements._3.MarkerPostTypeConverter.convert(MarkerPostTypeConverter.java:52)
        at org.hisrc.tenra.converter.commontransportelements._3.MarkerPostTypeConverter.convert(MarkerPostTypeConverter.java:19)
        at org.hisrc.tenra.builder.ModelBuilder.addMarkerPost(ModelBuilder.java:152)
        at org.hisrc.tenra.builder.ModelBuilder.add(ModelBuilder.java:85)
        at org.hisrc.tenra.parser.Parser.parsePayload(Parser.java:102)
        at org.hisrc.tenra.parser.Parser.parseFeatureCollection(Parser.java:89)
        at org.hisrc.tenra.parser.Parser.parseFeatureCollection(Parser.java:87)
        at org.hisrc.tenra.parser.Parser.parseFeatureCollection(Parser.java:87)
        at org.hisrc.tenra.parser.Parser.parseFeatureCollection(Parser.java:87)
        at org.hisrc.tenra.parser.Parser.parseFeatureCollection(Parser.java:87)
        at org.hisrc.tenra.parser.Parser.parse(Parser.java:65)
        at org.hisrc.tenra.processor.Processor.process(Processor.java:36)
        at org.hisrc.tenra.Main.main(Main.java:18)
```

**Comment by highsource** [comment]
I've already adjusted and reconverted it, stay tuned, will be committed next days.

**Comment by schulmar** [comment]
You mean the geojson files will be put on the opendata portal within the next days?

**Comment by highsource** [comment]
That may take some time since DB Netz normally wants to check if files are kosher.
I meant I'll push my changes in tenra next days, you can easily convert the data on your own.

**Comment by schulmar** [comment]
Okay, thanks for the clarification. I understood reconverted together with commited as you will send it to DB Netz. Anyways, thanks for the great work.

**Comment by highsource** [comment]
I can release GeoJSON on my own unofficially but not via DB OpenData portal (yet).

**Comment by schulmar** [comment]
I have no problem with loading unofficial data to try them out :)

**Comment by highsource** [comment]
Here you go.

**Comment by highsource** [comment]
https://www.dropbox.com/s/rm64tpr5rpda8jo/DB-Netz_GeoJSON_20160107.zip?dl=0
